# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.12.0"
  python_check_max: "3.14"

recipe:
  name: httpx2-split
  version: ${{ version }}

source:
  - target_directory: httpcore2
    url: https://pypi.org/packages/source/h/httpcore2/httpcore2-${{ version }}.tar.gz
    sha256: 9293522bba0aa7c4c8e9e3f040c16575bd8868e155a77fa30c7a9085a5eae648
  - target_directory: httpx2
    url: https://pypi.org/packages/source/h/httpx2/httpx2-${{ version }}.tar.gz
    sha256: 7631fe9887a8a2275f4a2540e053aa670fcc50742864a9ae7c66e609fdcf12cf

build:
  noarch: python
  number: 2

outputs:
  - package:
      name: httpcore2
      version: ${{ version }}
    build:
      noarch: python
      script:
        - cd httpcore2
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - hatch-fancy-pypi-readme
        - hatchling
        - pip
        - python ${{ python_min }}.*
        - uv-dynamic-versioning >=0.14.1
      run:
        - h11 >=0.16
        - python >=${{ python_min }}
        - truststore >=0.10
      extras:
        http2:
          - h2 >=3,<5
        socks:
          - socksio 1.*
        trio:
          - trio >=0.22.0,<1.0
        anyio:
          - anyio >=4.5.0,<5.0
    tests:
      - python:
          imports: httpcore2
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    about:
      homepage: https://pypi.org/project/httpcore2
      summary: A minimal low-level HTTP client.
      license_file: httpcore2/LICENSE.md

  - package:
      name: httpx2
    build:
      script:
        - cd httpx2
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - httpx2 = httpx2:main
    requirements:
      host:
        - hatch-fancy-pypi-readme
        - hatchling
        - pip
        - python ${{ python_min }}.*
        - uv-dynamic-versioning >=0.14.1
      run:
        - ${{ pin_subpackage("httpcore2", exact=true) }}
        - anyio >=4.10
        - idna >=3.18
        - python >=${{ python_min }}
        - truststore >=0.10
        - typing_extensions >=4.5.0
      extras:
        brotli:
          - brotli-python >=1.2.0
        cli:
          - click >=8.4.2
          - pygments 2.*
          - rich >=10,<16
        http2:
          - h2 >=3,<5
        socks:
          - socksio 1.*
        ws:
          - wsproto >=1.2
        zstd:
          - backports.zstd >=1.0.0
    tests:
      - python:
          imports: httpx2
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            # https://github.com/prefix-dev/rattler-build/pull/2813
            # - httpx2[extras=cli]
            - click >=8.4.2
            - pygments 2.*
            - rich >=10,<16
        script:
          env:
            PYTHONIOENCODING: utf-8
            PYTHONUTF8: "1"
          content:
            - httpx2 --help

about:
  homepage: https://pypi.org/project/httpx2
  summary: The next generation HTTP client.
  license: BSD-3-Clause
  repository: https://github.com/pydantic/httpx2
  license_file: httpx2/LICENSE.md

extra:
  feedstock-name: httpx2
  recipe-maintainers:
    - bollwyvl
    - Kludex
    - pavelzw
